### ISSUE TITLE
Quesion about the byol experiments

### ISSUE THREAD

**Issue by mingkai-zheng** [maple-research-lab/CLSA#3]
Hello, I have just seen that you have a generalization experiment on page 10, which cooperates CLSA with BYOL. Would you like to describe some details of this experiment?  I.e. what was the temperature in this experiment?  And what was the target distribution for stronger augmentation (i.e. the output of online network or EMA network)?

**Comment by wang3702** [comment]
Thanks a lot for your interest! We keep the same temperature as in MoCo experiment. Also, the target distribution is also similar to the MoCo framework, using the EMA network as a reference to calculate the relative distribution.
