### ISSUE TITLE
Stronger Augmentations

### ISSUE THREAD

**Issue by pikeyang** [maple-research-lab/CLSA#6]
Except for what you mentioned in the article ---
`we randomly select an augmentation from the above 14 types of transformations, and apply it to the image with a probability of 0.5. This process is repeated five times and that will strongly augment an image as the example shown in the right panel of Fig. 2.`

Have you tried to increase the intensity of the attack as stronger augmentations?

**Comment by wang3702** [comment]
Thank you for your interest! Sorry, we don't try the intensity of stronger augmentations. But I think it should be easy to try by simply modifying the augmentation script.
