### ISSUE TITLE
If I only want to calculate the first term of formula 6, how do I need to modify the code?

### ISSUE THREAD

**Issue by pikeyang** [maple-research-lab/CLSA#7]
<img width="559" alt="image" src="https://github.com/maple-research-lab/CLSA/assets/59758624/68f12e05-476b-4c04-933e-e1da97968635">

**Comment by wang3702** [comment]
You can simply do it modify this line
https://github.com/maple-research-lab/CLSA/blob/37df76cf5cb032683e57b70a3a4090f0d524c8fd/training/train.py#L57.
Basically, ignore any other indexes that compute the relationship between k and i.

**Comment by pikeyang** [comment]
thanks
